homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 331
  unit_system: imperial
  time_zone: America/Phoenix
  customize: !include_dir_merge_named customize
    
frontend:
updater:
discovery:
history:
logbook:
sun:

group: !include_dir_merge_named group
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation

http:
  server_port: 8123
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24

device_tracker:
  - platform: bluetooth_tracker
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret asuswrt_username
    password: !secret asuswrt_password

media_player:
  - platform: cast

zwave:
  usb_path: /dev/zwaveusbstick
  config_path: /usr/local/share/python-openzwave/config

notify:
  - name: file
    platform: file
    filename: notification_log
    timestamp: true
  - name: push
    platform: html5
    gcm_api_key: !secret html5_gcm_api_key
    gcm_sender_id: !secret html5_gcm_sender_id

ifttt:
  key: !secret ifttt_api_key
