homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 33.3133
  longitude: -111.9948
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 331
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Phoenix
  customize:
    sensor.pws_weather:
      friendly_name: 'Weather'
    sensor.pws_temp_f:
      friendly_name: 'Temperature'
    sensor.pws_feelslike_f:
      friendly_name: 'Feels Like'
    sensor.pws_wind_gust_mph:
      friendly_name: 'Wind Gust'
    sensor.pws_wind_string:
      friendly_name: 'Wind'
    sensor.pws_precip_1hr_in:
      friendly_name: 'Rainfall (last hour)'
    sensor.pws_precip_today_in:
      friendly_name: 'Rainfall (today)'
    sensor.pws_dewpoint_f:
      friendly_name: 'Dewpoint'
    sensor.pws_pressure_in:
      friendly_name: 'Pressure'
    sensor.pws_relative_humidity:
      friendly_name: 'Humidity'
    sensor.pws_UV:
      friendly_name: 'UV'
    sensor.pws_visibility_mi:
      friendly_name: 'Visibility'
    sensor.pws_elevation:
      friendly_name: 'Elevation'
    sensor.pws_location:
      friendly_name: 'Location'
    sensor.pws_observation_time:
      friendly_name: 'Last Updated'
    media_player.living_room_home:
      friendly_name: 'Google Home'
    sensor.vision_zp3111_multisensor_4in1_luminance_2_3:
      friendly_name: 'Luminance'
    sensor.vision_zp3111_multisensor_4in1_relative_humidity_2_5:
      friendly_name: 'Humidity'
    sensor.vision_zp3111_multisensor_4in1_temperature_2_1:
      friendly_name: 'Temperature'
    sensor.vision_zp3111_multisensor_4in1_burglar_2_10:
      friendly_name: 'Motion'
    sensor.badlogin:
      friendly_name: 'Login Failures (Weekly)'
    
# Enables the frontend
frontend:

http:
  server_port: 8123
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - dewpoint_f
      - feelslike_f
      - heat_index_f
      - elevation
      - location
      - observation_time
      - precip_1hr_in
      - precip_today_in
      - pressure_in
      - relative_humidity
      - temp_f
      - UV
      - visibility_mi
      - weather
      - wind_gust_mph
      - wind_mph
      - wind_string
  - platform: template
    sensors:
      living_room_motion:
        friendly_name: 'Motion Detected'
        value_template: >-
          {%- if is_state("sensor.vision_zp3111_multisensor_4in1_burglar_2_10", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}
  - platform: command_line
    command: grep -c 'WARNING \[nginx-auth\] Ban' /var/log/fail2ban.log
    name: badlogin

device_tracker:
  - platform: bluetooth_tracker
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret asuswrt_username
    password: !secret asuswrt_password

#--------------------------
#   Groups
#--------------------------

group:
  default_view:
    view: yes
    entities:
      - group.weather
      - group.people
      - group.devices
      - group.living_room
      - group.admin
  weather:
    name: Weather
    entities:
      - sensor.pws_weather
      - sensor.pws_temp_f
      - sensor.pws_feelslike_f
      - sensor.pws_relative_humidity
      - sensor.pws_wind_gust_mph
      - sensor.pws_wind_string
      - sensor.pws_precip_1hr_in
      - sensor.pws_precip_today_in
      - sensor.pws_dewpoint_f
      - sensor.pws_pressure_in
      - sensor.pws_UV
      - sensor.pws_visibility_mi
      - sensor.pws_elevation
      - sensor.pws_location
      - sensor.pws_observation_time
  people:
    name: People
    entities:
      - device_tracker.android9d38228c46e82699
      - device_tracker.pjsiphone
  devices:
    name: Devices
    entities:
      - device_tracker.grantsmbp
      - device_tracker.raspberrypi
      - device_tracker.lmdvgshive1932
  living_room:
    name: Living Room
    entities:
      - sensor.vision_zp3111_multisensor_4in1_luminance_2_3
      - sensor.vision_zp3111_multisensor_4in1_relative_humidity_2_5
      - sensor.vision_zp3111_multisensor_4in1_temperature_2_1
      - sensor.living_room_motion
      - media_player.living_room_home
  admin:
    name: admin
    entities:
      - sensor.badlogin

#--------------------------
#   Z-Wave
#--------------------------

zwave:
  usb_path: /zwaveusbstick
  config_path: /usr/local/share/python-openzwave/config

automation:
  - alias: Z-Wave network is complete
    trigger:
      platform: event
      event_type: zwave.network_complete
    action:
      service: notify.file
      data:
        message: 'Z-Wave network is complete'
  - alias: Z-Wave network is ready
    trigger:
      platform: event
      event_type: zwave.network_ready
    action:
      service: notify.file
      data:
        message: 'Z-Wave network is ready'
  - alias: Z-Wave network is starting
    trigger:
      platform: event
      event_type: zwave.network_start
    action:
      service: notify.file
      data:
        message: 'Z-Wave network is starting'
  - alias: Z-Wave network is stopping
    trigger:
      platform: event
      event_type: zwave.network_stop
    action:
      service: notify.file
      data:
        message: 'Z-Wave network is stopping'
  - alias: Grant is home
    trigger:
      platform: state
      entity_id: device_tracker.android9d38228c46e82699
      state: 'home'
    action:
      service: notify.push
      data:
        message: 'Grant is home!'
  - alias: Grant left home
    trigger:
      platform: state
      entity_id: device_tracker.android9d38228c46e82699
      state: 'not_home'
    action:
      service: notify.push
      data:
        message: 'Grant left home.'
  - alias: PJ is home
    trigger:
      platform: state
      entity_id: device_tracker.pjsiphone
      state: 'home'
    action:
      service: notify.push
      data:
        message: 'PJ is home!'
  - alias: PJ left home
    trigger:
      platform: state
      entity_id: device_tracker.pjsiphone
      state: 'not_home'
    action:
      service: notify.push
      data:
        message: 'PJ left home.'


#--------------------------
#   Notifications
#--------------------------

notify:
  - name: file
    platform: file
    filename: notification_log
    timestamp: true
  - name: push
    platform: html5
    gcm_api_key: !secret html5_gcm_api_key
    gcm_sender_id: !secret html5_gcm_sender_id
