- platform: template
  sensors:
    pantry_motion:
      friendly_name: 'Pantry Motion'
      value_template: >-
        {%- if states('sensor.pantry_sensor_burglar_5_10') == 'unknown' -%}
            N/A
        {%- elif is_state('sensor.pantry_sensor_burglar_5_10', '0') -%}
            No
        {%- else -%}
            Yes
        {%- endif -%}