- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - dewpoint_f
    - feelslike_f
    - heat_index_f
    - elevation
    - location
    - observation_time
    - precip_1hr_in
    - precip_today_in
    - pressure_in
    - relative_humidity
    - temp_f
    - UV
    - visibility_mi
    - weather
    - wind_gust_mph
    - wind_mph
    - wind_string
