- platform: broadlink
  host: 192.168.1.163
  mac: 34:EA:34:E7:EC:7D
  timeout: 15
  switches:
    # TV
    living_room_tv_power:
      friendly_name: Living Room TV Power
      command_on: JgBYAAABJ5QSExMSEzcTExITEhMSExMSEzcTNxQSEjgSOBI4EjgTNxITFBETExM3EhMSExITEhMTNxQ2EzgTEhI2FDgSOBI4EwAFFgABKEkTAAxVAAEnShIADQU=
      command_off: JgBYAAABJ5QSExMSEzcTExITEhMSExMSEzcTNxQSEjgSOBI4EjgTNxITFBETExM3EhMSExITEhMTNxQ2EzgTEhI2FDgSOBI4EwAFFgABKEkTAAxVAAEnShIADQU=
    # Receiver
    living_room_receiver_power:
      friendly_name: Living Room Receiver Power
      command_on: JgCqAE8TJxQTFCgTExUnFBIVExQTFBMVEhUTFCcUJxQTFBMAAsFOFCYVEhUnFBMUJxQTFBMUExUTFBMUExQnFCcUExUSAALBThQnFBMUJxQTFCgTExQTFRMUExQTFRIVJhUmFRIVEwACwE8TJxQTFCcUExUmFRIVExQTFBMVEhUTFCgTJxQTFBMAAsFNFSYVExQmFRMUJxQTFBMUExUTFBMUExUmFCgTExUSAA0FAAAAAAAAAAAAAAAAAAA=
      command_off: JgCqAE8TJxQTFCgTExUnFBIVExQTFBMVEhUTFCcUJxQTFBMAAsFOFCYVEhUnFBMUJxQTFBMUExUTFBMUExQnFCcUExUSAALBThQnFBMUJxQTFCgTExQTFRMUExQTFRIVJhUmFRIVEwACwE8TJxQTFCcUExUmFRIVExQTFBMVEhUTFCgTJxQTFBMAAsFNFSYVExQmFRMUJxQTFBMUExUTFBMUExUmFCgTExUSAA0FAAAAAAAAAAAAAAAAAAA=
    living_room_receiver_volume_up:
      friendly_name: Living Room Receiver Volume Up
      command_on: JgCIAE4UFBMnFBMUExUnFBIVExQTFBMVEhUUEycUJhUUExMAAtROFBMVJhQTFRMUJhUTFBMUFBQTFBMUFBQnEycUExUSAALVThQTFCYVFBMTFCcUExUSFRMUExQTFRIVJhUnFBMUFAAC004UExQnFBMUExUnFBIVExQTFBMVExQTFCcUJxQTFBMADQU=
      command_off: JgCIAE4UFBMnFBMUExUnFBIVExQTFBMVEhUUEycUJhUUExMAAtROFBMVJhQTFRMUJhUTFBMUFBQTFBMUFBQnEycUExUSAALVThQTFCYVFBMTFCcUExUSFRMUExQTFRIVJhUnFBMUFAAC004UExQnFBMUExUnFBIVExQTFBMVExQTFCcUJxQTFBMADQU=
    living_room_receiver_volume_down:
      friendly_name: Living Room Receiver Volume Down
      command_on: JgBmAE4VJhQoExMVEhUmFRMUExQTFRIVExQTFCgTJxQUExMAAsFNFSYVJxQSFRMUKBMTFBMVExQTFBMUExUnFCYVExQTAALATxMnFCcUExQTFSYUFBQTFBMUExQTFRMUJhUnFBMUEwANBQAA
      command_off: JgBmAE4VJhQoExMVEhUmFRMUExQTFRIVExQTFCgTJxQUExMAAsFNFSYVJxQSFRMUKBMTFBMVExQTFBMUExUnFCYVExQTAALATxMnFCcUExQTFSYUFBQTFBMUExQTFRMUJhUnFBMUEwANBQAA
    living_room_receiver_mute:
      friendly_name: Living Room Receiver Mute
      command_on: JgBmAE4UExUUEyYVExQmFRMUFRITFRMUFRIVEyYUJxQTFRIAAtVNFRIVFRInFBMUKRIVExQTFRITFBMVFBMmFSgTExQVAALQUBQUExMVJhQTFSYVExQTFBMVFBMTFBMUKRInFBUSFQANBQAA
      command_off: JgBmAE4UExUUEyYVExQmFRMUFRITFRMUFRIVEyYUJxQTFRIAAtVNFRIVFRInFBMUKRIVExQTFRITFBMVFBMmFSgTExQVAALQUBQUExMVJhQTFSYVExQTFBMVFBMTFBMUKRInFBUSFQANBQAA
    # Photo Frame
    living_room_photo_frame_power:
      friendly_name: Living Room Photo Frame Power
      command_on: JgBYAAABJ5UUNREUERQSExEUExISExMSExISFBEUETgRFBITERQSOBITERQSExEUETgTNxE4ERQTNxE4EjcSOBITEhMSExI4EgAF3wABJ0oTAAxXAAEnShIADQU=
      command_off: JgBYAAABJ5UUNREUERQSExEUExISExMSExISFBEUETgRFBITERQSOBITERQSExEUETgTNxE4ERQTNxE4EjcSOBITEhMSExI4EgAF3wABJ0oTAAxXAAEnShIADQU=
